Document: qscreenshotter
Title: Debian qscreenshotter Manual
Author: <insert document author here>
Abstract: This manual describes what qscreenshotter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qscreenshotter/qscreenshotter.sgml.gz

Format: postscript
Files: /usr/share/doc/qscreenshotter/qscreenshotter.ps.gz

Format: text
Files: /usr/share/doc/qscreenshotter/qscreenshotter.text.gz

Format: HTML
Index: /usr/share/doc/qscreenshotter/html/index.html
Files: /usr/share/doc/qscreenshotter/html/*.html
